name: aeb_lint
description: Linter for my Dart projects
version: 1.1.0
homepage: https://github.com/aeb-dev/aeb_lint
repository: https://github.com/aeb-dev/aeb_lint
issues: https://github.com/aeb-dev/aeb_lint/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
